### ISSUE TITLE
前后端可以直接联调使用了吗？

### ISSUE THREAD

**Issue by 172151295** [wkclz/xxl-job-ruoyi-vue3#1]

**Comment by 172151295** [comment]
我用后端xxl-job-admin-oracle版本老是报错大佬，还有GLUE WEB部分没有实现

**Comment by wkclz** [comment]
只要前端的还原度足够大，可以直接调用后端的。
报错具体信息是什么呢？感觉是跨域错误，如果你的后端是在 k8s, 或者 nginx 之后，可以在 k8s 或者 nginx 上解决跨域问题
解决方案还得提供更具体的错误提示才行

**Comment by 172151295** [comment]
> 只要前端的还原度足够大，可以直接调用后端的。
> 报错具体信息是什么呢？感觉是跨域错误，如果你的后端是在 k8s, 或者 nginx 之后，可以在 k8s 或者 nginx 上解决跨域问题
> 解决方案还得提供更具体的错误提示才行

我可以加您微信吗？
