### ISSUE TITLE
我用后端xxl-job-admin-oracle版本老是报错大佬，还有GLUE WEB部分没有实现

### ISSUE THREAD

**Issue by 172151295** [wkclz/xxl-job-ruoyi-vue3#2]

**Comment by wkclz** [comment]
确实，我偷懒了，GLUE WEB 部分没做，我这里的场景没涉及 GLUE WEB。
近期我补上。

**Comment by 172151295** [comment]
我可以加你微信吗？

**Comment by 172151295** [comment]
> 确实，我偷懒了，GLUE WEB 部分没做，我这里的场景没涉及 GLUE WEB。
> 近期我补上。

微信号发我一下或者Q

**Comment by wkclz** [comment]
微信：shrimp0_0
加了之后我删除此条回复

**Comment by 172151295** [comment]
> 微信：shrimp0_0
> 加了之后我删除此条回复

加您了

**Comment by 172151295** [comment]
> 微信：shrimp0_0
> 加了之后我删除此条回复
Pluto是我微信
